/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 grillz3.glb -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/grillz3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Low_Teeth25_Low_Teeth25_0" geometry={nodes.Low_Teeth25_Low_Teeth25_0.geometry} material={materials['Material.001']} position={[-0.821, 0.174, -3.803]} scale={16.333} />
      <mesh name="Low_Teeth25_Low_Teeth25_0001" geometry={nodes.Low_Teeth25_Low_Teeth25_0001.geometry} material={materials['Material.001']} position={[-0.821, 0.139, -3.396]} scale={16.333} />
      <mesh name="Low_Teeth25_Low_Teeth25_0002" geometry={nodes.Low_Teeth25_Low_Teeth25_0002.geometry} material={materials['Material.001']} position={[-0.821, -0.75, -3.803]} scale={16.333} />
      <mesh name="Low_Teeth25_Low_Teeth25_0003" geometry={nodes.Low_Teeth25_Low_Teeth25_0003.geometry} material={materials['Material.001']} position={[-0.821, -0.75, -3.803]} scale={16.333} />
    </group>
  )
}

useGLTF.preload('/grillz3.glb')
